version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: core@123
      MYSQL_DATABASE1: automation
    ports:
      - "3306:3306"
    volumes:
      - mysql_data3:/var/lib/mysql
    networks:
      - my-network


  backend:
    depends_on:
      - db 
    build: ./.
    restart: always
    ports:
      - "9082:9082"
    environment:
      DB_HOST: db
      MYSQL_ROOT_PASSWORD: core@123
      MYSQL_DATABASE: automation
      SPRING_PROFILES_ACTIVE: docker
      spring.datasource.url: jdbc:mysql://db:3306/automation?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      spring.datasource.username: root
      spring.datasource.password: core@123
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql_data3:
